language: generic

services:
  - docker

install:
  - docker build -t stable stable
  - docker build -t loki loki
  - docker build -t loki-unstable loki-unstable
  - docker build -t juno-stable juno-stable
  - docker build -t juno-stable-installer juno-stable-installer
  - docker build -t juno-unstable juno-unstable
  - docker build -t juno-unstable-installer juno-unstable-installer

script:
  - echo BUILDS PASSED
